# Generated by Django 5.2.1 on 2025-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_available_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowingrecord',
            name='status',
            field=models.CharField(choices=[('NONE', 'No borrowed books'), ('BORROWED', 'Borrowed'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='NONE', max_length=10),
        ),
    ]
