# Generated by Django 5.2.1 on 2025-05-18 03:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowingrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='borrowingrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='borrowingrecord',
            index=models.Index(fields=['user', 'status'], name='api_borrowi_user_id_08b6e8_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowingrecord',
            index=models.Index(fields=['book', 'status'], name='api_borrowi_book_id_071626_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowingrecord',
            index=models.Index(fields=['due_date'], name='api_borrowi_due_dat_e68a37_idx'),
        ),
    ]
